[project]
name = "ba-thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Simon Münker", email = "muenker@uni-trier.de" }
]
requires-python = ">=3.11"
dependencies = [
    "polars>=1.41.2",
    "rich>=15.0.0",
]

[project.scripts]
ba-thesis = "ba_thesis:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
